name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  publish:
    name: upload release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: snok/install-poetry@v1

      - uses: actions/cache@v3
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-Linux-3.11-${{ hashFiles('**/pyproject.toml') }}

      - name: build
        run: make build

      - name: Sanity test
        run: | 
          pip install dist/*.whl --force-reinstall

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        
      - name: create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}

