name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: snok/install-poetry@v1

      - uses: actions/cache@v3
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-Linux-3.11-${{ hashFiles('**/pyproject.toml') }}

      - name: build
        run: make build

      - name: Sanity test
        run: | 
          pip install dist/*.whl --force-reinstall

      - name: create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
