name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  check-if-publish-needed:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      publish_needed: ${{ steps.changed-files.outputs.any_changed  }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            pyre/__init__.py

  pypi-publish:
    name: upload release to PyPI
    needs: check-if-publish-needed
    if: needs.check-if-publish-needed.outputs.publish_needed == 'true'
    runs-on: ubuntu-latest
    environment: pypi
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: snok/install-poetry@v1

      - uses: actions/cache@v3
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-Linux-3.11-${{ hashFiles('**/pyproject.toml') }}

      - name: build
        run: make build

      - name: Sanity test
        run: | 
          pip install dist/*.whl --force-reinstall

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        
      - name: create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
